name: Check

on:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - run: npm ci
        name: Instaall

      - run: npm run lint
        name: Lint

      - run: docker-compose up -d mongodb redis
        name: Start infrastructure

      - run: npm run test
        name: Tests

      - run: docker-componse down
        name: Dispose infrastructure
